version: '3.1'

services:
  redmine:
    image: arm64v8/redmine:latest
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: arm64v8/mysql:8.0.33
    restart: always
    container_name: redmine_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine